### PR TITLE
Do not set accept-encoding on behalf of cloudflare

### PR DESCRIPTION
**Pull request by fourdim**

### CODE REVIEW

**Comment by JohnMaguire** [comment]
Thanks! This indeed solves my issue (#5).

I wonder if it would make sense to take an allow-list approach here instead of copying the original incoming request and stripping the known invalid headers?

**Comment by fourdim** [comment]
https://github.com/aws/aws-sdk-js/blob/master/lib/signers/v4.js#L191-L199
The official s3 sdk is also using the blacklist model.
There are many headers that can help prevent security vulnerabilities.
Removing them might not be a good idea.

**Comment by JohnMaguire** [comment]
> [aws/aws-sdk-js@`49f5d76`/lib/signers/v4.js#L191-L199](https://github.com/aws/aws-sdk-js/blob/49f5d76b417615de1f928d6cfdf9af60e6cc9ca0/lib/signers/v4.js#L191-L199) The official s3 sdk is also using the blacklist model. There are many headers that can help prevent security vulnerabilities. Removing them might not be a good idea.

@fourdim I could be mistaken, but I believe that the `unsignableHeaders` in the linked file serves a slightly different purpose than the `UNSIGNABLE_HEADERS` in this file. The note in the file mentions:

```
// These headers appear in the request, but are not passed upstream
```

In other words, Cloudflare seems to filter these headers from the outgoing request, so including them in the signature generates an erroneous signature.

I _believe_ that in the file you linked, these are headers which will typically be overwritten by an HTTP client (e.g. something like cURL) with appropriate values based on the payload (e.g. `content-length`) and may be altered by a proxy or are otherwise sensitive (e.g. `authorization`) and therefore Amazon has decided not to use them as part of the signature calculation.

As far as security goes, are there any particular security headers you had in mind that might apply here? I'm familiar with security headers that clients and servers send, such as to prevent MIME sniffing, cross-origin requests, etc. but my mental model would be that it is actually safer to construct a new request here with known headers to the upstream, than to allow the client control over the headers that are sent to B2. However, I can't think of anything particularly nefarious here off the top of my head, and I'm curious if there's a header the client might be sending that would provide security value by passing it along to B2.

**Comment by fourdim** [comment]
I'm not a security expert but this might be an example: https://w3c.github.io/webappsec-fetch-metadata
In addition to the security related headers, it is also troublesome to enumerate all the headers needed.

**Comment by albicasty** [comment]
super, great job

**Comment by gillbates** [comment]
@fourdim @JohnMaguire 

or anyone from b2 could specify a whitelist for headers there?
Otherwise, it could be non functional once again when cloudflare changes something in the header forwarded there.

**Comment by metadaddy** [comment]
Thanks for the contribution, @fourdim!

The root cause seems to be a recently-introduced Cloudflare-ism: [Upcoming Change To Accept Encoding Header](https://community.cloudflare.com/t/upcoming-change-to-accept-encoding-header/517115).

[This doc](https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#accept-encoding) is related, but I'm not sure if it needs to be updated in light of the above change. I'll do a quick investigation on where `accept-encoding` gets clobbered - on the way in to the worker, or the way upstream to B2 - and whether B2 actually acts on that header.

**Comment by JohnMaguire** [comment]
@gillbates Agreed, this is what I was getting at in my above message. I think that there is no reason to send all of the downstream request headers to the upstream - just the headers necessary to load the file properly.

**Comment by JohnMaguire** [comment]
> I'm not a security expert but this might be an example: [w3c.github.io/webappsec-fetch-metadata](https://w3c.github.io/webappsec-fetch-metadata) In addition to the security related headers, it is also troublesome to enumerate all the headers needed.

I just got around to reading the spec you sent and I'm not sure I see how it applies here. It looks like it's a CSRF mitigation - from the introduction:

> It would be helpful if servers could make more intelligent decisions about whether or not to respond to a given request based on the way that it’s made in order to mitigate the latter category. For example, it seems pretty unlikely that a "Transfer all my money" endpoint on a bank’s server would expect to be referenced from an [img](https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element) tag, and likewise unlikely that evil.com is going to be making any legitimate requests whatsoever. Ideally, the server could reject these requests a priori rather than delivering them to the application backend.

However, AFAIK Backblaze B2 is simply a static file host, so you can't trick it into taking some application-level action on the user's behalf (such as transferring their funds.)

I'm also not quite sure what you mean by "enumerate all the headers needed." I'm proposing that rather than using the incoming Request object, we form a new simple GET Request object and sign only the headers the new Request contains. I don't think there is a reason to pass along the browser's headers to Backblaze B2 (this is perhaps more useful for the sister project, https://github.com/backblaze-b2-samples/cloudflare-b2-proxy, which acts as a simple proxy.)

**Comment by gillbates** [comment]
> Thanks for the contribution, @fourdim!
> 
> The root cause seems to be a recently-introduced Cloudflare-ism:
> 
> * [Upcoming Change To Accept Encoding Header](https://community.cloudflare.com/t/upcoming-change-to-accept-encoding-header/517115).
> * [Content compression from origin servers to the Cloudflare network](https://developers.cloudflare.com/speed/optimization/content/brotli/content-compression/)
> 
> I'll do a quick investigation into how B2 actually acts on that header, and how Cloudflare operates on the content, and either merge your PR as-is, or tweak it to set the outgoing `accept-encoding` to the same value that Cloudflare overwrites it with.

Yes. Please just update a whitelist function in your script to provide b2 only headers. In this case, any future changes by cloudflare or any other downstream providers will not make it stop working ...

**Comment by metadaddy** [comment]
I did some investigation here:
* Regardless of what the client sends, Cloudflare sets the accept-encoding header to `gzip, br` in the incoming HTTP request before it gets to the worker
* Regardless of what the worker sends, Cloudflare sets the accept-encoding header to `gzip` in the outgoing HTTP request after the worker is done with it

So it looks like the best way forward is to add accept-encoding to the list of unsignable headers - i.e. merge this PR.

I'm reluctant to just pick a set of HTTP headers to allow-list, since that risks future problems if/when B2 adds new functionality.

So, once I've merged this change, I'll add the ability to optionally specify an allow-list, `ALLOWABLE_HEADERS`, in configuration.

**Comment by metadaddy** [comment]
Added ability to optionally specify an allow-list, ALLOWABLE_HEADERS, in configuration: 6970948c30f2fe04415b1c90305d2dd6e8d8af09.

**Comment by KintaMiao** [comment]
@metadaddy 
I am using the latest code, which contains `accept-encoding`, but it still shows SignatureDoesNotMatch when accessing through Cloudflare.
How can I modify the configuration file?

**Pull request merged**
